# Generated by Django 5.2.4 on 2025-09-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='products',
            name='seat_capacity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
