# Generated by Django 5.2.4 on 2025-09-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='userpic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
